-- ==============================================================================
-- ENGINEER'S GOT TALENT 2.0 (EGT 2.0) - SUPABASE SQL DATABASE SCHEMA & MIGRATION
-- Run this complete SQL script in your Supabase SQL Editor (https://supabase.com/dashboard)
-- ==============================================================================

-- 0. CREATE REGISTRATION SEQUENCES (for auto-generating EGT2-P-0001 / EGT2-T-0001)
CREATE SEQUENCE IF NOT EXISTS day1_reg_seq START WITH 1;
CREATE SEQUENCE IF NOT EXISTS day2_reg_seq START WITH 1;

-- 1. CREATE DAY 1 REGISTRATIONS TABLE (STAGE ARENA - SOLO & GROUP ACTS)
CREATE TABLE IF NOT EXISTS public.day1_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reg_id VARCHAR(50) UNIQUE DEFAULT ('EGT2-P-' || LPAD(CAST(nextval('day1_reg_seq'::regclass) AS TEXT), 4, '0')),
    full_name TEXT NOT NULL,
    uid VARCHAR(50) NOT NULL UNIQUE,
    email TEXT NOT NULL,
    phone VARCHAR(20) NOT NULL,
    department TEXT DEFAULT 'AIT CSE',
    academic_year TEXT DEFAULT '3rd Year',
    section TEXT NOT NULL,
    group_name TEXT NOT NULL,
    block TEXT NOT NULL,
    category TEXT NOT NULL,
    requires_audio_track TEXT DEFAULT 'No',
    audio_track_url TEXT,
    entry_type TEXT DEFAULT 'Solo',
    team_name TEXT,
    team_members TEXT,
    team_members_raw TEXT,
    performance_desc TEXT,
    previous_performance_link TEXT,
    instagram TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CREATE DAY 2 REGISTRATIONS TABLE (TECH WIZARDS ARENA - SQUADS)
CREATE TABLE IF NOT EXISTS public.day2_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reg_id VARCHAR(50) UNIQUE DEFAULT ('EGT2-T-' || LPAD(CAST(nextval('day2_reg_seq'::regclass) AS TEXT), 4, '0')),
    leader_name TEXT NOT NULL,
    uid VARCHAR(50) NOT NULL UNIQUE,
    email TEXT NOT NULL,
    phone VARCHAR(20) NOT NULL,
    department TEXT DEFAULT 'AIT CSE',
    academic_year TEXT DEFAULT '3rd Year',
    section TEXT NOT NULL,
    group_name TEXT NOT NULL,
    block TEXT NOT NULL,
    squad_name TEXT NOT NULL,
    
    -- Combined Teammate Strings
    teammate_1 TEXT NOT NULL,
    teammate_2 TEXT NOT NULL,
    teammate_3 TEXT DEFAULT '',
    
    -- Separated Teammate Fields (Name, UID, Section, Group, Block)
    teammate_1_name TEXT,
    teammate_1_uid VARCHAR(50),
    teammate_1_section TEXT,
    teammate_1_group TEXT,
    teammate_1_block TEXT,

    teammate_2_name TEXT,
    teammate_2_uid VARCHAR(50),
    teammate_2_section TEXT,
    teammate_2_group TEXT,
    teammate_2_block TEXT,

    teammate_3_name TEXT,
    teammate_3_uid VARCHAR(50),
    teammate_3_section TEXT,
    teammate_3_group TEXT,
    teammate_3_block TEXT,
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 3. MIGRATION ALTER COMMANDS (Run if tables already exist in your Supabase)
-- ==============================================================================

-- ----------------------------------------------------
-- DAY 1 TABLE ALTER MIGRATIONS
-- ----------------------------------------------------
ALTER TABLE public.day1_registrations 
ADD COLUMN IF NOT EXISTS entry_type TEXT DEFAULT 'Solo',
ADD COLUMN IF NOT EXISTS department TEXT DEFAULT 'AIT CSE',
ADD COLUMN IF NOT EXISTS academic_year TEXT DEFAULT '3rd Year',
ADD COLUMN IF NOT EXISTS section TEXT,
ADD COLUMN IF NOT EXISTS group_name TEXT,
ADD COLUMN IF NOT EXISTS block TEXT,
ADD COLUMN IF NOT EXISTS requires_audio_track TEXT DEFAULT 'No',
ADD COLUMN IF NOT EXISTS audio_track_url TEXT,
ADD COLUMN IF NOT EXISTS team_name TEXT,
ADD COLUMN IF NOT EXISTS team_members TEXT,
ADD COLUMN IF NOT EXISTS team_members_raw TEXT;

-- Set default for entry_type to 'Solo'
ALTER TABLE public.day1_registrations 
ALTER COLUMN entry_type SET DEFAULT 'Solo';

-- ----------------------------------------------------
-- DAY 2 TABLE ALTER MIGRATIONS
-- ----------------------------------------------------
ALTER TABLE public.day2_registrations 
ADD COLUMN IF NOT EXISTS section TEXT,
ADD COLUMN IF NOT EXISTS group_name TEXT,
ADD COLUMN IF NOT EXISTS block TEXT,
ADD COLUMN IF NOT EXISTS teammate_1 TEXT,
ADD COLUMN IF NOT EXISTS teammate_2 TEXT,
ADD COLUMN IF NOT EXISTS teammate_3 TEXT,
ADD COLUMN IF NOT EXISTS teammate_1_name TEXT,
ADD COLUMN IF NOT EXISTS teammate_1_uid VARCHAR(50),
ADD COLUMN IF NOT EXISTS teammate_1_section TEXT,
ADD COLUMN IF NOT EXISTS teammate_1_group TEXT,
ADD COLUMN IF NOT EXISTS teammate_1_block TEXT,
ADD COLUMN IF NOT EXISTS teammate_2_name TEXT,
ADD COLUMN IF NOT EXISTS teammate_2_uid VARCHAR(50),
ADD COLUMN IF NOT EXISTS teammate_2_section TEXT,
ADD COLUMN IF NOT EXISTS teammate_2_group TEXT,
ADD COLUMN IF NOT EXISTS teammate_2_block TEXT,
ADD COLUMN IF NOT EXISTS teammate_3_name TEXT,
ADD COLUMN IF NOT EXISTS teammate_3_uid VARCHAR(50),
ADD COLUMN IF NOT EXISTS teammate_3_section TEXT,
ADD COLUMN IF NOT EXISTS teammate_3_group TEXT,
ADD COLUMN IF NOT EXISTS teammate_3_block TEXT;

-- Drop unused tech_stack and github_link columns from Day 2
ALTER TABLE public.day2_registrations 
DROP COLUMN IF EXISTS tech_stack,
DROP COLUMN IF EXISTS github_link;

-- ----------------------------------------------------
-- UNIQUE UID CONSTRAINTS (Block Duplicate Registrations)
-- ----------------------------------------------------
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'day1_uid_unique'
    ) THEN
        ALTER TABLE public.day1_registrations ADD CONSTRAINT day1_uid_unique UNIQUE (uid);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'day2_uid_unique'
    ) THEN
        ALTER TABLE public.day2_registrations ADD CONSTRAINT day2_uid_unique UNIQUE (uid);
    END IF;
END $$;

-- ----------------------------------------------------
-- ROW LEVEL SECURITY (RLS) & POLICIES
-- ----------------------------------------------------
ALTER TABLE public.day1_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.day2_registrations ENABLE ROW LEVEL SECURITY;

-- Allow anyone to register (Public INSERT)
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert to day1'
    ) THEN
        CREATE POLICY "Allow public insert to day1" ON public.day1_registrations FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert to day2'
    ) THEN
        CREATE POLICY "Allow public insert to day2" ON public.day2_registrations FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE policyname = 'Allow authenticated read to day1'
    ) THEN
        CREATE POLICY "Allow authenticated read to day1" ON public.day1_registrations FOR SELECT USING (auth.role() = 'authenticated');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE policyname = 'Allow authenticated read to day2'
    ) THEN
        CREATE POLICY "Allow authenticated read to day2" ON public.day2_registrations FOR SELECT USING (auth.role() = 'authenticated');
    END IF;
END $$;
