import { createClient } from '@supabase/supabase-js'

// Retrieve Supabase environment variables from Vite
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || ''
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || ''

// Check if valid credentials are supplied
export const isSupabaseConfigured = Boolean(
  supabaseUrl && 
  supabaseAnonKey && 
  !supabaseUrl.includes('your-supabase-project-id')
)

// Initialize Supabase client
export const supabase = isSupabaseConfigured
  ? createClient(supabaseUrl, supabaseAnonKey)
  : null

// SUPABASE AUTHENTICATION HELPERS
export async function signInAdmin(email, password) {
  if (!supabase) {
    return { success: false, error: 'Supabase credentials not configured in environment variables (VITE_SUPABASE_URL & VITE_SUPABASE_ANON_KEY).' }
  }
  try {
    const { data, error } = await supabase.auth.signInWithPassword({
      email,
      password
    })
    if (error) {
      return { success: false, error: error.message }
    }
    return { success: true, data }
  } catch (err) {
    return { success: false, error: err.message || 'Supabase authentication failed.' }
  }
}

export async function signUpAdmin(email, password) {
  if (!supabase) {
    return { success: false, error: 'Supabase credentials not configured in environment variables.' }
  }
  try {
    const { data, error } = await supabase.auth.signUp({
      email,
      password
    })
    if (error) {
      return { success: false, error: error.message }
    }
    return { success: true, data }
  } catch (err) {
    return { success: false, error: err.message || 'Supabase account creation failed.' }
  }
}

export async function signOutAdmin() {
  if (supabase) {
    try {
      await supabase.auth.signOut()
    } catch (err) {
      console.warn('Signout exception:', err)
    }
  }
}

export async function getAdminSession() {
  if (!supabase) return null
  try {
    const { data } = await supabase.auth.getSession()
    return data?.session || null
  } catch (err) {
    console.warn('Get session exception:', err)
    return null
  }
}

// ----------------------------------------------------
// REGISTRATION SYSTEM WITH BACKEND-GENERATED UNIQUE IDs
// EGT2-P-0001 -> Performer (Day 1)
// EGT2-A-0001 -> Audience
// EGT2-T-0001 -> Technical (Day 2)
// ----------------------------------------------------

export async function saveDay1Registration(data) {
  const cleanUid = data.uid.trim().toUpperCase()

  // 1. Check for Duplicate UID in Supabase
  if (supabase) {
    try {
      const { data: existing } = await supabase
        .from('day1_registrations')
        .select('uid, full_name, reg_id')
        .ilike('uid', cleanUid)

      if (existing && existing.length > 0) {
        return {
          success: false,
          error: `Student UID [${cleanUid}] is already registered for Day 1 (${existing[0].reg_id}). Duplicate registrations are not allowed.`
        }
      }
    } catch (err) {
      console.warn('Supabase UID check warning:', err)
    }
  }

  // 2. Check local fallback storage
  const localItems = getFromLocalStorage('egt_day1_registrations')
  const localDuplicate = localItems.find(item => item.uid?.trim().toUpperCase() === cleanUid)
  if (localDuplicate) {
    return {
      success: false,
      error: `Student UID [${cleanUid}] is already registered for Day 1 (${localDuplicate.reg_id}). Duplicate registrations are not allowed.`
    }
  }

  // Payload for backend insertion (reg_id generated by Supabase backend sequence / trigger)
  const insertPayload = {
    full_name: data.fullName.trim(),
    uid: cleanUid,
    email: data.email.trim(),
    phone: data.phone.trim(),
    department: data.department || 'CSE',
    academic_year: data.academicYear || '3rd Year',
    category: data.category,
    entry_type: data.entryType,
    team_name: data.teamName || '',
    team_members: data.teamMembers || '',
    performance_desc: data.performanceDesc || '',
    previous_performance_link: data.previousPerformanceLink || '',
    instagram: data.instagram || '',
    status: 'pending',
    created_at: new Date().toISOString()
  }

  // 3. Insert into Supabase (Backend generates unique EGT2-P-0001 reg_id)
  if (supabase) {
    try {
      const { data: dbData, error } = await supabase
        .from('day1_registrations')
        .insert([insertPayload])
        .select()

      if (!error && dbData && dbData.length > 0) {
        saveToLocalStorage('egt_day1_registrations', dbData[0])
        return { success: true, data: dbData[0], isSupabase: true }
      } else if (error && (error.code === '23505' || error.message.includes('unique'))) {
        return {
          success: false,
          error: `Student UID [${cleanUid}] is already registered! Duplicate registrations are not allowed.`
        }
      }
    } catch (err) {
      console.warn('Supabase insert exception, falling back to local:', err)
    }
  }

  // 4. Local Fallback storage with sequential EGT2-P-XXXX format
  const nextSeq = String(localItems.length + 1).padStart(4, '0')
  const localPayload = {
    reg_id: `EGT2-P-${nextSeq}`,
    ...insertPayload
  }

  saveToLocalStorage('egt_day1_registrations', localPayload)
  return { success: true, data: localPayload, isSupabase: false }
}

export async function saveDay2Registration(data) {
  const cleanUid = data.uid.trim().toUpperCase()

  // 1. Check for Duplicate UID in Supabase
  if (supabase) {
    try {
      const { data: existing } = await supabase
        .from('day2_registrations')
        .select('uid, leader_name, reg_id')
        .ilike('uid', cleanUid)

      if (existing && existing.length > 0) {
        return {
          success: false,
          error: `Student UID [${cleanUid}] is already registered for Day 2 (${existing[0].reg_id}). Duplicate registrations are not allowed.`
        }
      }
    } catch (err) {
      console.warn('Supabase UID check warning:', err)
    }
  }

  // 2. Check local fallback storage
  const localItems = getFromLocalStorage('egt_day2_registrations')
  const localDuplicate = localItems.find(item => item.uid?.trim().toUpperCase() === cleanUid)
  if (localDuplicate) {
    return {
      success: false,
      error: `Student UID [${cleanUid}] is already registered for Day 2 (${localDuplicate.reg_id}). Duplicate registrations are not allowed.`
    }
  }

  // Payload for backend insertion (reg_id generated by Supabase backend sequence / trigger)
  const insertPayload = {
    leader_name: data.fullName.trim(),
    uid: cleanUid,
    email: data.email.trim(),
    phone: data.phone.trim(),
    department: data.department || 'CSE',
    academic_year: data.academicYear || '3rd Year',
    squad_name: data.squadName || '',
    teammate_1: data.teammate1 || '',
    teammate_2: data.teammate2 || '',
    github_link: data.githubLink || '',
    tech_stack: data.techStack || 'C++',
    status: 'pending',
    created_at: new Date().toISOString()
  }

  // 3. Insert into Supabase (Backend generates unique EGT2-T-0001 reg_id)
  if (supabase) {
    try {
      const { data: dbData, error } = await supabase
        .from('day2_registrations')
        .insert([insertPayload])
        .select()

      if (!error && dbData && dbData.length > 0) {
        saveToLocalStorage('egt_day2_registrations', dbData[0])
        return { success: true, data: dbData[0], isSupabase: true }
      } else if (error && (error.code === '23505' || error.message.includes('unique'))) {
        return {
          success: false,
          error: `Student UID [${cleanUid}] is already registered! Duplicate registrations are not allowed.`
        }
      }
    } catch (err) {
      console.warn('Supabase insert exception, falling back to local:', err)
    }
  }

  // 4. Local Fallback storage with sequential EGT2-T-XXXX format
  const nextSeq = String(localItems.length + 1).padStart(4, '0')
  const localPayload = {
    reg_id: `EGT2-T-${nextSeq}`,
    ...insertPayload
  }

  saveToLocalStorage('egt_day2_registrations', localPayload)
  return { success: true, data: localPayload, isSupabase: false }
}

// Fetch all Day 1 Registrations
export async function getDay1Registrations() {
  if (supabase) {
    try {
      const { data, error } = await supabase
        .from('day1_registrations')
        .select('*')
        .order('created_at', { ascending: false })

      if (!error && data) {
        return data
      }
    } catch (err) {
      console.warn('Failed to fetch from Supabase:', err)
    }
  }
  return getFromLocalStorage('egt_day1_registrations')
}

// Fetch all Day 2 Registrations
export async function getDay2Registrations() {
  if (supabase) {
    try {
      const { data, error } = await supabase
        .from('day2_registrations')
        .select('*')
        .order('created_at', { ascending: false })

      if (!error && data) {
        return data
      }
    } catch (err) {
      console.warn('Failed to fetch from Supabase:', err)
    }
  }
  return getFromLocalStorage('egt_day2_registrations')
}

// Update Status (Approve / Reject / Waitlist)
export async function updateRegistrationStatus(table, regId, status) {
  if (supabase) {
    try {
      await supabase
        .from(table)
        .update({ status })
        .eq('reg_id', regId)
    } catch (err) {
      console.warn('Supabase update failed:', err)
    }
  }

  const localKey = table === 'day1_registrations' ? 'egt_day1_registrations' : 'egt_day2_registrations'
  const items = getFromLocalStorage(localKey)
  const updated = items.map(item => item.reg_id === regId ? { ...item, status } : item)
  localStorage.setItem(localKey, JSON.stringify(updated))
}

// Delete Registration
export async function deleteRegistration(table, regId) {
  if (supabase) {
    try {
      await supabase
        .from(table)
        .delete()
        .eq('reg_id', regId)
    } catch (err) {
      console.warn('Supabase delete failed:', err)
    }
  }

  const localKey = table === 'day1_registrations' ? 'egt_day1_registrations' : 'egt_day2_registrations'
  const items = getFromLocalStorage(localKey)
  const filtered = items.filter(item => item.reg_id !== regId)
  localStorage.setItem(localKey, JSON.stringify(filtered))
}

// Storage Helpers
function saveToLocalStorage(key, payload) {
  const existing = JSON.parse(localStorage.getItem(key) || '[]')
  existing.unshift(payload)
  localStorage.setItem(key, JSON.stringify(existing))
}

function getFromLocalStorage(key) {
  return JSON.parse(localStorage.getItem(key) || '[]')
}
